theme: jekyll-theme-minimal
title: Dooseop Choi
description: Senior Researcher, Artificial Intelligence Research Lab., ETRI
logo: /images/DChoi.PNG

# Site Footer
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:eona1301@email.com
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url:                                        # 이런식으로 url을 주석처리하면 노출되지 않습니다.
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/eona1301"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/eona1301"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/danghyeona/"
