theme: jekyll-theme-minimal
title: Dooseop Choi
description: Senior Researcher, Artificial Intelligence Research Lab., ETRI
logo: /images/DChoi.PNG

# Site Author
author:
  name             : "Dang Hyeona"                  # 이름 영역입니다.
  avatar           : "image/profile/2020me.jpg"     # 프로필 사진 경로입니다.
  bio              : "**기록이 자산!!**<br>매일 공부하고 있습니다.<br>소통을 좋아합니다."
                     # biography의 약칭으로, 자기소개를 적으시면 됩니다.
                     # 줄바꿈은 <br>로 굵은 글씨는 **글씨** 로 표기해주세요. 
  location         : "Republic of Korea"            # 지역 입니다. 
  email            : # 이메일 주소입니다. (links에서 작성할 수 있기 때문에 생략하였습니다.)
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:eona1301@email.com
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/eona1301"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/eona1301"
    - label: "Instagram"                            # 표시되는 이름입니다.
      icon: "fab fa-fw fa-instagram"                # fab fa-fw fa-{SNS NAME} 으로 해주세요.
      url: "https://www.instagram.com/danghyeona/"  # 개인 SNS 계정 링크를 기재하면 됩니다.
